# Generated by Django 4.2.20 on 2025-04-30 02:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('capacity', models.PositiveIntegerField()),
                ('seating_plan', models.ImageField(blank=True, null=True, upload_to='venue_seating_plans/')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10)),
                ('seat_type', models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium'), ('vip', 'VIP'), ('disabled', 'Disabled Access')], default='standard', max_length=10)),
                ('row', models.CharField(max_length=5)),
                ('section', models.CharField(max_length=50)),
                ('x_coord', models.FloatField(help_text='X coordinate (0-100) for seat positioning')),
                ('y_coord', models.FloatField(help_text='Y coordinate (0-100) for seat positioning')),
                ('is_booked', models.BooleanField(default=False)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='booking.venue')),
            ],
            options={
                'unique_together': {('venue', 'seat_number')},
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='event_images/')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('premium_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('vip_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('disabled_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='booking.venue')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.event')),
                ('seats', models.ManyToManyField(to='booking.seat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
